# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'ifood-mobile-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ifood-mobile-test
    pod 'TwitterKit'
    pod 'Alamofire'
    pod 'ObjectMapper', '~> 3.3'
    pod 'SDWebImage', '~> 4.0'

  target 'ifood-mobile-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ifood-mobile-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
